#!/bin/bash
set -o nounset
# set -o errexit

# Change the following two lines when releasing a new assignment
readonly LAB="lab8"
readonly CLASSES="*"
readonly DEADLINE="2021-04-20 00:01 +0800"

cutoff_time=$(date -d "$DEADLINE" +%s)
current_time=$(date +%s)
if [ "$current_time" -gt "$cutoff_time" ]; then
  late_by=$(((current_time - $cutoff_time)/60))
  cat << HERE
The deadline (including any extension allowed) for this assignment has passed. You are late by $late_by minutes.  Unless you have prior approval from the instructors, this submission will be considered a late submission and you will be subjected to a grade penalty as spelled out in the module policy.

Press Control-C to abort, enter to submit.
HERE
  read
fi

#get git username from git config
readonly GIT_USER=$(git config --get github.user)

if [ -z $GIT_USER ]; then
  cat << HERE
Please configure your Github username on CS2030S PE hosts before running this script.  You can do so by editing the ~/.gitconfig file.  Details can be found in the CS2030S Lab Guide.
HERE
  exit 1
fi

#check if under git repository
git remote get-url origin &> /dev/null
if [ "$?" -ne "0" ]; then
  cat << HERE
You are not under a git repository directory.  Please navigate to the directory for ${LAB} and submit again.
HERE
  exit 1
fi

#get reponame
readonly GITORG="nus-cs2030s-2021-s2"
readonly REPO="$LAB-$GIT_USER"
read -ra fileset <<< "$CLASSES"

if [ "${PWD##*/}" != $REPO ]; then
  cat << HERE
You are not under your lab directory.  Please navigate to the directory ${REPO} and submit again.
HERE
  exit 1
fi

#check if under correct assignment repo
localrepo=`git remote get-url origin`
if [[ ! $localrepo =~ .*[:/]$GITORG/$REPO.git$ ]]; then
  cat << HERE
Your current directory is for the git repository below:
  $localrepo
Please navigate to the directory for ${LAB} and submit again.
HERE
  exit 1
fi

# add commit and push
#for class in "${fileset[@]}"; do
#  if [ ! -e $class.java ]; then
#   echo "$class.java does not exist. It is not submitted."
# else
#   git add $class.java
# fi
#done
git add *.java
for deleted_file in $(git ls-files --deleted); do
  git rm $deleted_file
done
got_change=$(git status --porcelain)

# commit a copy of the change to submit-history branch
git checkout submit-history -q
# commit changes to master branch
if [ "$got_change" != "" ]; then
  git commit -m "Individual submission" -m "$got_change"
fi

# back to master, cherry pick the last commit, and squash
git checkout master -q
if [ "$got_change" != "" ]; then
  git cherry-pick submit-history
  first_commit=`git log --oneline | tail -1 | cut -d" " -f 1`
  # squash history
  git reset --soft $first_commit 
  git commit -m "Cumulative submission" 

  # now push everything
  git push --force --all

  if [ "$?" -ne "0" ]; then
    cat << HERE
Submission FAILED.

Check that your .gitconfig is configured properly and your GitHub password is entered correctly.  If you are sure everything has been done correct, send a copy of the output above to a member of the CS2030S teaching team.
HERE
    exit 1
  else
    cat << HERE
You have successfully submitted your code.  You can view your submission online at:
https://github.com/$GITORG/$REPO
HERE
  fi
else
  git push --force --all
fi
